# Generated by Django 6.0.3 on 2026-04-21 18:02

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated list of emails to receive notifications')),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManufactureYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Years of Manufacture',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': ' Vehicle Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('contact', models.PositiveIntegerField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('change_message', models.TextField(blank=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('has_extended', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_auctions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_auctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_no', models.CharField(max_length=255, unique=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_cc', models.IntegerField()),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255)),
                ('color', models.CharField(default='white', max_length=10)),
                ('seats', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('idle', 'idle'), ('available', 'available'), ('on_auction', 'on_auction'), ('on_bid', 'on_bid'), ('bid_won', 'bid_won'), ('sold', 'sold'), ('stop_sale', 'stop_sale')], default='idle', max_length=10)),
                ('reserve_price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('file', models.FileField(default='images/default-vehicle.png', upload_to='images/')),
                ('views', models.IntegerField(default=0)),
                ('financed', models.BooleanField(default=False)),
                ('financing_percentage', models.IntegerField(blank=True, null=True)),
                ('is_hotsale', models.BooleanField(default=False)),
                ('is_flashsale', models.BooleanField(default=False)),
                ('flashsale_price', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disapproved_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('Financier', models.ForeignKey(blank=True, default='MyCredit Ltd', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.financier')),
                ('YOM', models.ForeignKey(default='2010', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.manufactureyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vehicles', to=settings.AUTH_USER_MODEL)),
                ('disapproved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disapproved_vehicles', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(default='petrol', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.fueltype')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Marked_as_sold_by', to=settings.AUTH_USER_MODEL)),
                ('body_type', models.ForeignKey(default='Vehicle', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehiclebody')),
                ('make', models.ForeignKey(default='Vehicle', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehiclemake')),
                ('model', models.ForeignKey(default='SUV', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehiclemodel')),
                ('yard', models.ForeignKey(blank=True, default='Riverlong', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.yard')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('price_revision', 'Price Revision'), ('bid_awarded', 'Bid Awarded'), ('bid_disqualified', 'Bid Disqualified')], max_length=50)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiddingFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_fees', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_fees', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('referred_by', models.TextField(blank=True, null=True)),
                ('is_auction_bid', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('disqualification_comment', models.TextField(blank=True, null=True)),
                ('awarded', models.BooleanField(default=False)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(blank=True, help_text='The specific auction this bid belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vehicles.auction')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_by', to=settings.AUTH_USER_MODEL)),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='vehicles.vehicle')),
            ],
            options={
                'permissions': [('can_mark_bid_paid', 'Can mark awarded bids as paid')],
            },
        ),
        migrations.CreateModel(
            name='AwardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarder', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('on_bid', models.BooleanField(default=False)),
                ('returned_to_available', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auction_history', to='vehicles.auction')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auction_history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': ' Auction Histories',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='vehicles',
            field=models.ManyToManyField(related_name='auctions', to='vehicles.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='images/default-vehicle.png', upload_to='vehicleimages/')),
                ('vehicle', models.ForeignKey(default='images/default-vehicle.png', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='VehiclePriceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_revisions', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_approved', 'status', '-created_at'], name='idx_v_approved_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make'], name='idx_v_make'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='idx_v_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_hotsale', '-created_at'], name='idx_v_hotsale'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_flashsale', '-created_at'], name='idx_v_flashsale'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-created_at'], name='idx_v_created_desc'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-views'], name='idx_v_views_desc'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['file'], name='idx_v_file'),
        ),
    ]
