# Generated by Django 6.0.4 on 2026-04-22 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_type', models.CharField(choices=[('text', 'Text Note'), ('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('text_note', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='payment_proofs/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/pdfs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note visible only to staff', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmation', to='vehicles.bidding')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_confirmations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Confirmation',
                'verbose_name_plural': 'Payment Confirmations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
