# Generated by Django 5.2.7 on 2026-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_paymentconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=10),
        ),
    ]
