# Generated by Django 5.2.7 on 2026-04-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_upcomingauction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingauction',
            name='location',
        ),
    ]
