# Generated by Django 6.0.4 on 2026-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_merge_20260428_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingauction',
            options={'ordering': ['auction_startdate'], 'verbose_name': 'Upcoming Auction', 'verbose_name_plural': 'Upcoming Auctions'},
        ),
        migrations.RenameField(
            model_name='upcomingauction',
            old_name='auction_date',
            new_name='auction_startdate',
        ),
        migrations.AddField(
            model_name='upcomingauction',
            name='auction_enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingauction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('archived', 'Archived')], default='draft', max_length=15),
        ),
    ]
