"""
Django settings for auctions project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', default=False, cast=bool)

DEBUG = False

ALLOWED_HOSTS = ['*' ]

# Application definition

CSRF_TRUSTED_ORIGINS = [
    'https://98b9-197-237-29-119.ngrok-free.app'
]

INSTALLED_APPS = [
    'django.contrib.admin',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'vehicles',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    'django_social_share',
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.sitemaps',
    # 'django_daraja',
    # 'simple_history',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'vehicles.middleware.AdminActionLogMiddleware',
    # 'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'auctions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auctions.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 60,  # keep alive for 60s
    }
}
# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.mysql',
# 		'NAME': 'autobid',
# 		'USER': 'root',
# 		'PASSWORD': '',
# 		'HOST':'localhost',
# 		'PORT':'3306',
# 	}
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
    {
        'NAME': 'auctions.validators.FourDigitPinValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'staticfiles'),
# ]
# LOGIN_REDIRECT_URL = 'homepage'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
LOGOUT_URL = 'homepage'
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles_build","static")
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
LOGIN_URL = 'login'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Security
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
CKEDITOR_UPLOAD_PATH = "uploads/"  # Folder where uploaded files will go
CKEDITOR_IMAGE_BACKEND = 'pillow'  # Required for image processing (pillow is a common dependency)
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',  # Use full toolbar (you can customize this)
        'height': 300,
        'width': 800,
    },
}
ADMIN_NOTIFICATION_EMAILS = ['mmburu@riverlong.com']

SECURE_CONTENT_TYPE_NOSNIFF = False  # Allow CDN scripts to load
TIARA_API_URL = config('TIARA_API_URL')
AUTH_TOKEN = config('AUTH_TOKEN')


# # M-Pesa Daraja Settings
# MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY')
# MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET')
# MPESA_SHORTCODE = config('MPESA_SHORTCODE')
# MPESA_PASSKEY = config('MPESA_PASSKEY')
# MPESA_SANDBOX_MODE = True
# MPESA_ENVIRONMENT = 'sandbox'
# MPESA_EXPRESS_SHORTCODE = config('MPESA_EXPRESS_SHORTCODE')
# MPESA_SHORTCODE_TYPE = 'paybill'
#
# # URLs (auto switch between sandbox and production)
# if MPESA_ENVIRONMENT == 'sandbox':
#     MPESA_BASE_URL = "https://sandbox.safaricom.co.ke"
# else:
#     MPESA_BASE_URL = "https://api.safaricom.co.ke"


MPESA_CONFIG = {
    "ENVIRONMENT": "sandbox",
    "CONSUMER_KEY": config('MPESA_CONSUMER_KEY'),
    "CONSUMER_SECRET": config('MPESA_CONSUMER_SECRET'),
    "SHORTCODE": "174379",                    # Sandbox shortcode
    "PASSKEY": config('MPESA_PASSKEY'),       # From Daraja portal
    "CALLBACK_URL": config('MPESA_CALLBACK_URL'),
    "BIDDING_FEE_AMOUNT": 1,                  # KES
}